CREATE TABLE BANKRECONCILATIONS
(
  BANKRECONCILATIONID varchar(200) NOT NULL,
  ACCOUNTID varchar(200) NOT NULL,
  DURATION varchar(255) NOT NULL,
  CREDITTRANSFER varchar(255) NOT NULL,
  INTERESTRECEIVED varchar(255) NOT NULL,
  STALECHQSREVERSED varchar(255) NOT NULL,
  BANKCHARGES varchar(255) NOT NULL,
  DEBITTRANSFER varchar(255) NOT NULL,
  OUTSTANDINGSTALECHQS varchar(255) NOT NULL,
  UNPRESENTEDCHQS varchar(255) NOT NULL,
  BANKNOTCASHBOOK varchar(255) NOT NULL,
  UNCREDITEDLODGEMENTS varchar(255) NOT NULL,
  CASHBOOKNOTBANK varchar(255) NOT NULL,
  DIFFBTWBANKANDCASHBOOK varchar(255) NOT NULL,
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_BANKRECONCILATIONS PRIMARY KEY (BANKRECONCILATIONID)
);

ALTER TABLE BANKRECONCILATIONS ADD CONSTRAINT FK_BANKRECONCILATIONS_ACCT
  FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BANKRECONCILATIONS TO  SYSDBA WITH GRANT OPTION;




