CREATE TABLE BANKRECONCILATIONS
(
  BANKRECONCILATIONID varchar(200) NOT NULL,
  ACCOUNTID varchar(200) NOT NULL,
  DURATION varchar(100) NOT NULL,
  CREDITTRANSFER decimal(10,2) NOT NULL,
  INTERESTRECEIVED decimal(10,2) NOT NULL,
  STALECHQSREVERSED decimal(10,2) NOT NULL,
  BANKCHARGES decimal(10,2) NOT NULL,
  DEBITTRANSFER decimal(10,2) NOT NULL,
  OUTSTANDINGSTALECHQS decimal(10,2) NOT NULL,
  UNPRESENTEDCHQS decimal(10,2) NOT NULL,
  BANKNOTCASHBOOK decimal(10,2) NOT NULL,
  UNCREDITEDLODGEMENTS decimal(10,2) NOT NULL,
  CASHBOOKNOTBANK decimal(10,2) NOT NULL,
  DIFFBTWBANKANDCASHBOOK decimal(10,2) NOT NULL,
  ISDELETED boolean NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_BANKRECONCILATIONS PRIMARY KEY (BANKRECONCILATIONID)
);

ALTER TABLE BANKRECONCILATIONS ADD CONSTRAINT FK_BANKRECONCILATIONS_ACCT
  FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BANKRECONCILATIONS TO  SYSDBA WITH GRANT OPTION;




