CREATE TABLE MAINTAINBALANCES
(
  MAINTAINBALANCEID varchar(200) NOT NULL,
  ACCOUNTID varchar(200) NOT NULL,
  OPENINGBALANCE varchar(255) NOT NULL,
  CLOSINGBALANCE varchar(255),
  DURATION varchar(255) NOT NULL,
  STATUS integer NOT NULL,
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_MAINTAINBALANCE PRIMARY KEY (MAINTAINBALANCEID)
);

ALTER TABLE MAINTAINBALANCES ADD CONSTRAINT FK_MAINTAINBALANCES_ACCOUNTS
  FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MAINTAINBALANCES TO  SYSDBA WITH GRANT OPTION;




