CREATE TABLE MAINTAINYEARLYBALANCES
(
  MAINTAINYEARLYBALANCEID varchar(200) NOT NULL,
  ACCOUNTID varchar(200) NOT NULL,
  OPENINGBALANCE varchar(255) NOT NULL,
  CLOSINGBALANCE varchar(255),
  CURRENTYEAR varchar(255) NOT NULL,
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_MAINTAINYEARLYBALANCES PRIMARY KEY (MAINTAINYEARLYBALANCEID)
);

ALTER TABLE MAINTAINYEARLYBALANCES ADD CONSTRAINT FK_MAINTAINYEARLYBALANCES_ACC
  FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MAINTAINYEARLYBALANCES TO  SYSDBA WITH GRANT OPTION;




