CREATE TABLE ORGANIZATIONS
(
  ORGANIZATIONID varchar(200) NOT NULL,
  ORGANIZATIONNAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  TINNUMBER varchar(255),
  CONTACTPERSON varchar(255),
  CONTACTNUMBER varchar(255),
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_ORGANIZATIONS PRIMARY KEY (ORGANIZATIONID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ORGANIZATIONS TO  SYSDBA WITH GRANT OPTION;




