CREATE TABLE TRANSACTIONDESCRIPTIONS
(
  TRANSACTIONDESCRIPTIONID varchar(200) NOT NULL,
  DESCRIPTIONNAME varchar(255),
  TRANSACTIONTYPE varchar(255),
  DESCRIPTION varchar(255),
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_TRANSACTIONDESCRIPTIONS PRIMARY KEY (TRANSACTIONDESCRIPTIONID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON TRANSACTIONDESCRIPTIONS TO  SYSDBA WITH GRANT OPTION;




