CREATE TABLE TRANSACTIONS
(
  TRANSACTIONID varchar(200) NOT NULL,
  ACCOUNTID varchar(200) NOT NULL,
  AMMOUNTWITHDRAWN varchar(255) NOT NULL,
  AMMOUNTDEPOSITED varchar(255) NOT NULL,
  NAMEOFBENEFICIARY varchar(255) NOT NULL,
  DATEOFTRANSACTION date NOT NULL,
  PVORRVNUMBER varchar(255) NOT NULL,
  SUBHEADCOLUMN varchar(255) NOT NULL,
  TRANSACTIONDESCRIPTIONID varchar(200) NOT NULL,
  REFNUMBER varchar(255) NOT NULL,
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTIONID)
);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_ACC
  FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS (ACCOUNTID);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_TRANSDESC
  FOREIGN KEY (TRANSACTIONDESCRIPTIONID) REFERENCES TRANSACTIONDESCRIPTIONS (TRANSACTIONDESCRIPTIONID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON TRANSACTIONS TO  SYSDBA WITH GRANT OPTION;




