CREATE TABLE USERS
(
  USERID varchar(200) NOT NULL,
  USERNAME varchar(255) NOT NULL,
  USERPASSWORD varchar(255) NOT NULL,
  FULLNAME varchar(255) NOT NULL,
  TELEPHONENUMBER varchar(255) NOT NULL,
  EMAILADDRESS varchar(255) NOT NULL,
  SECURITYQUESTION varchar(255) NOT NULL,
  SECURITYANSWER varchar(255) NOT NULL,
  PICTURE blob sub_type 0,
  ISDELETED smallint NOT NULL,
  CREATEDAT timestamp NOT NULL,
  UPDATEDAT timestamp NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (USERID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USERS TO  SYSDBA WITH GRANT OPTION;




